Remove storybook-addons from peerDependencies
kadirahq/storybook-addon-options pull request #11
Opened 2016-12-22 10:05 UTC by thebuilder

@kadira/storybook-addons is already a dependency of "@kadira/storybook". You shouldn't need to install in manually.

2017-03-31 10:27 UTC, ndelangen commented
Thank you for contributing!
`storybook-addons` is required in this code path:
https://github.com/storybooks/storybook-addon-options/blob/f12e5541e8bca798beb7d4189975f70cfce381d8/src/manager/index.js#L2

So **not** declaring this dependency would be incorrect?

peerDependencies should not have to be installed manually, where did you find this information? Did you run into an error when **not** installing manually? If so, that sounds like a bug to me.

2017-03-31 10:28 UTC, ndelangen requested changes

2017-03-31 10:28 UTC, ndelangen commented on package.json
> -    "@kadira/storybook-addons": "^1.5.0",
This is actually needed?

2017-03-31 10:50 UTC, thebuilder commented
The reason for this was to get rid of the package installation warning you get:
```
warning "@kadira/storybook-addon-options@1.0.2" has unmet peer dependency "@kadira/storybook-addons@^1.5.0".
```

I realise `storybook-addons-options` requires `storybook-addons`,  but since you will always use options with Storybook itself, and Storybook has added the dependency for `storybook-addons` to its ´package.json`.

2017-03-31 11:08 UTC, ndelangen commented
If you could provide a simple reproduction path to how to get this warning, I can try that locally.

Sounds like the installation happens in the wrong order.

2017-04-15 15:13 UTC, ndelangen commented
Hey @thebuilder  

Thank you so much for this PR! We're moving over to a mono-repo, since that makes a lot of sense for a project like this.
We would ❤️ it if you could create a PR here: https://github.com/storybooks/storybook

That'd be awesome, thanks!

2017-04-15 15:13 UTC, closed without merging